init_url  = "gemini://geminiprotocol.net/"
#init_url = "gemini://medusae.space"
#init_url = "gemini://datapulp.smol.pub/"

scroll_at = 6

[colors]
 #p.black[3]    = "#202020"

 #p.dyellow[3]  = "#706050"
 #p.yellow[3]   = "#c0b090"

 #p.dred[3]     = "#402020"
 #p.dgreen[3]   = "#183018"
 #p.dcyan[3]    = "#103040"
 #p.dmagenta[3] = "#402030"

 #p.red[3]      = "#d06060"
 #p.green[3]    = "#70a070"
 #p.cyan[3]     = "#90a0d0"
 #p.magenta[3]  = "#a070a0"

# black
background = "202020" 
# dyellow
border     = "706050"
badlink    = "706050"
banner     = "706050"
# yellow
text       = "c0b090"
list       = "c0b090"
dialog     = "c0b090"
# cyan
link       = "90a0d0"
# green
preformat  = "70a070"
quote      = "70a070"
# red
heading1   = "d06060"
heading2   = "d06060"
heading3   = "d06060"

[format]
x_margin    = 12
y_margin    = 2
list_prefix = " - "
heading3    = [3, 2]
heading2    = [2, 1]
heading1    = [1, 0]

[keys]
global    = "g"
msg_view  = "m"
tab_view  = "t"
load_cfg  = "c"

move_up      = "o"
move_down    = "i"
move_left    = "e"
move_right   = "n"
cycle_left   = "E"
cycle_right  = "N"
inspect      = "w"
delete_tab   = "v"
new_tab      = "p"

ack          = "y"
yes          = "y"
no           = "n"
